#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("helps.Droid.Resource", IsApplication=true)]

namespace helps.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::helps.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::helps.Droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int year = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int accent = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int accentPressed = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int primary = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int primaryDark = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int primaryMuted = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int primaryMutedPressed = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int transparent = 2131099654;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int corner_radius = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int form_margin = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int layer_padding = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int layout_padding = 2131165186;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int apptheme_textfield_activated_holo_light = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apptheme_textfield_default_holo_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int apptheme_textfield_disabled_focused_holo_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int apptheme_textfield_disabled_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int apptheme_textfield_focused_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int flat_selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int helps_logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_social_share = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_launcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int rect_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int register = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b000f
			public const int FinishDetailsInput = 2131427343;
			
			// aapt resource value: 0x7f0b0025
			public const int LinearLayout1 = 2131427365;
			
			// aapt resource value: 0x7f0b0001
			public const int Ttoolbar = 2131427329;
			
			// aapt resource value: 0x7f0b0010
			public const int TtoolbarTransparent = 2131427344;
			
			// aapt resource value: 0x7f0b002b
			public const int amvMenu = 2131427371;
			
			// aapt resource value: 0x7f0b002c
			public const int amvMenu2 = 2131427372;
			
			// aapt resource value: 0x7f0b0028
			public const int buttonAddToDo = 2131427368;
			
			// aapt resource value: 0x7f0b002a
			public const int checkToDoItem = 2131427370;
			
			// aapt resource value: 0x7f0b000d
			public const int country = 2131427341;
			
			// aapt resource value: 0x7f0b0011
			public const int forgotLayout = 2131427345;
			
			// aapt resource value: 0x7f0b0013
			public const int forgotPassword = 2131427347;
			
			// aapt resource value: 0x7f0b0012
			public const int forgotStudentId = 2131427346;
			
			// aapt resource value: 0x7f0b001e
			public const int helpsLogo = 2131427358;
			
			// aapt resource value: 0x7f0b000e
			public const int language = 2131427342;
			
			// aapt resource value: 0x7f0b0002
			public const int linearLayout1 = 2131427330;
			
			// aapt resource value: 0x7f0b0008
			public const int linearLayout2 = 2131427336;
			
			// aapt resource value: 0x7f0b0003
			public const int linearLayout3 = 2131427331;
			
			// aapt resource value: 0x7f0b0017
			public const int linearLayout4 = 2131427351;
			
			// aapt resource value: 0x7f0b001a
			public const int linearLayout5 = 2131427354;
			
			// aapt resource value: 0x7f0b0029
			public const int listViewToDo = 2131427369;
			
			// aapt resource value: 0x7f0b0021
			public const int loginBtn = 2131427361;
			
			// aapt resource value: 0x7f0b0020
			public const int loginPassword = 2131427360;
			
			// aapt resource value: 0x7f0b001f
			public const int loginStudentId = 2131427359;
			
			// aapt resource value: 0x7f0b0030
			public const int logout = 2131427376;
			
			// aapt resource value: 0x7f0b001c
			public const int mainlayout = 2131427356;
			
			// aapt resource value: 0x7f0b002e
			public const int menu_refresh = 2131427374;
			
			// aapt resource value: 0x7f0b002f
			public const int menu_settings = 2131427375;
			
			// aapt resource value: 0x7f0b002d
			public const int menu_share = 2131427373;
			
			// aapt resource value: 0x7f0b0009
			public const int radioButton1 = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int radioButton2 = 2131427338;
			
			// aapt resource value: 0x7f0b0018
			public const int registerEmail = 2131427352;
			
			// aapt resource value: 0x7f0b0015
			public const int registerFirstName = 2131427349;
			
			// aapt resource value: 0x7f0b0016
			public const int registerLastName = 2131427350;
			
			// aapt resource value: 0x7f0b001b
			public const int registerPassword = 2131427355;
			
			// aapt resource value: 0x7f0b0019
			public const int registerStudentId = 2131427353;
			
			// aapt resource value: 0x7f0b0014
			public const int relativeLayout1 = 2131427348;
			
			// aapt resource value: 0x7f0b0022
			public const int relativeLayout6 = 2131427362;
			
			// aapt resource value: 0x7f0b0000
			public const int relativeLayout66 = 2131427328;
			
			// aapt resource value: 0x7f0b001d
			public const int signInLayout = 2131427357;
			
			// aapt resource value: 0x7f0b000b
			public const int spinnerYear = 2131427339;
			
			// aapt resource value: 0x7f0b0027
			public const int textNewToDo = 2131427367;
			
			// aapt resource value: 0x7f0b0007
			public const int textView1 = 2131427335;
			
			// aapt resource value: 0x7f0b0023
			public const int textView2 = 2131427363;
			
			// aapt resource value: 0x7f0b0024
			public const int textView4 = 2131427364;
			
			// aapt resource value: 0x7f0b000c
			public const int textViewCountry = 2131427340;
			
			// aapt resource value: 0x7f0b0006
			public const int textViewFillUp = 2131427334;
			
			// aapt resource value: 0x7f0b0004
			public const int textViewName = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int textViewNameValue = 2131427333;
			
			// aapt resource value: 0x7f0b0026
			public const int textViewTitle = 2131427366;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_DetailsInput = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_ForgotPassword = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Activity_Register = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Activity_Sign_In = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Activity_To_Do = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Row_List_To_Do = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int toolbar = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int toolbarTransparent = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int activity_main = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int logout = 2131361793;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int blank = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int add_button_text = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int add_textbox_hint = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int checkbox_text = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int menu_refresh = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int mobile_services = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppBaseTheme = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int AppTheme = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int AppTheme_MyToolbar = 2131296259;
			
			// aapt resource value: 0x7f090007
			public const int AppTheme_NoStatus = 2131296263;
			
			// aapt resource value: 0x7f090004
			public const int AppTheme_SignIn = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int LightDialog = 2131296258;
			
			// aapt resource value: 0x7f090008
			public const int _AppTheme = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int standardEditText = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int whiteEditText = 2131296261;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
