#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("helps.Droid.Resource", IsApplication=true)]

namespace helps.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int accent = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int accentPressed = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int primary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primaryDark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int corner_radius = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int layer_padding = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int apptheme_edit_text_holo_light = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apptheme_textfield_activated_holo_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int apptheme_textfield_default_holo_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int apptheme_textfield_disabled_focused_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int apptheme_textfield_disabled_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int apptheme_textfield_focused_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int flat_selector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_social_share = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_launcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int rect_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rect_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int register = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int textlines = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public const int ForgotStudentIdIcon = 2131296260;
			
			// aapt resource value: 0x7f09001f
			public const int LinearLayout1 = 2131296287;
			
			// aapt resource value: 0x7f090001
			public const int Ttoolbar = 2131296257;
			
			// aapt resource value: 0x7f090025
			public const int amvMenu = 2131296293;
			
			// aapt resource value: 0x7f090022
			public const int buttonAddToDo = 2131296290;
			
			// aapt resource value: 0x7f090024
			public const int checkToDoItem = 2131296292;
			
			// aapt resource value: 0x7f090003
			public const int forgotLayout = 2131296259;
			
			// aapt resource value: 0x7f090007
			public const int forgotPassword = 2131296263;
			
			// aapt resource value: 0x7f090005
			public const int forgotStudentId = 2131296261;
			
			// aapt resource value: 0x7f09000a
			public const int imageView1 = 2131296266;
			
			// aapt resource value: 0x7f090010
			public const int imageView2 = 2131296272;
			
			// aapt resource value: 0x7f090014
			public const int imageView3 = 2131296276;
			
			// aapt resource value: 0x7f09000d
			public const int imageView5 = 2131296269;
			
			// aapt resource value: 0x7f090002
			public const int linearLayout1 = 2131296258;
			
			// aapt resource value: 0x7f090009
			public const int linearLayout3 = 2131296265;
			
			// aapt resource value: 0x7f09000f
			public const int linearLayout4 = 2131296271;
			
			// aapt resource value: 0x7f090013
			public const int linearLayout5 = 2131296275;
			
			// aapt resource value: 0x7f09000c
			public const int linearLayout6 = 2131296268;
			
			// aapt resource value: 0x7f090023
			public const int listViewToDo = 2131296291;
			
			// aapt resource value: 0x7f09001b
			public const int loginBtn = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int loginPassword = 2131296282;
			
			// aapt resource value: 0x7f090019
			public const int loginStudentId = 2131296281;
			
			// aapt resource value: 0x7f090017
			public const int mainlayout = 2131296279;
			
			// aapt resource value: 0x7f090027
			public const int menu_refresh = 2131296295;
			
			// aapt resource value: 0x7f090028
			public const int menu_settings = 2131296296;
			
			// aapt resource value: 0x7f090026
			public const int menu_share = 2131296294;
			
			// aapt resource value: 0x7f090016
			public const int register = 2131296278;
			
			// aapt resource value: 0x7f090011
			public const int registerEmail = 2131296273;
			
			// aapt resource value: 0x7f09000b
			public const int registerFirstName = 2131296267;
			
			// aapt resource value: 0x7f09000e
			public const int registerLastName = 2131296270;
			
			// aapt resource value: 0x7f090015
			public const int registerPassword = 2131296277;
			
			// aapt resource value: 0x7f090012
			public const int registerStudentId = 2131296274;
			
			// aapt resource value: 0x7f090008
			public const int relativeLayout1 = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int relativeLayout2 = 2131296262;
			
			// aapt resource value: 0x7f09001c
			public const int relativeLayout6 = 2131296284;
			
			// aapt resource value: 0x7f090000
			public const int relativeLayout66 = 2131296256;
			
			// aapt resource value: 0x7f090018
			public const int signInLayout = 2131296280;
			
			// aapt resource value: 0x7f090021
			public const int textNewToDo = 2131296289;
			
			// aapt resource value: 0x7f09001d
			public const int textView2 = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int textView4 = 2131296286;
			
			// aapt resource value: 0x7f090020
			public const int textViewTitle = 2131296288;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_ForgotPassword = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_Register = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Activity_Sign_In = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Activity_To_Do = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Row_List_To_Do = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int toolbar = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int activity_main = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int simple = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int add_button_text = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int add_textbox_hint = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int checkbox_text = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int menu_refresh = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int mobile_services = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int AppTheme_MyToolbar = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int AppTheme_NoStatus = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int AppTheme_SignIn = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int LightDialog = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int _AppTheme = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int standardEditText = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int whiteEditText = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
