#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("helps.Droid.Resource", IsApplication=true)]

namespace helps.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::helps.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::helps.Droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_from_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_from_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out_to_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_out_to_right = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090000
			public const int year = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070002
			public const int accent = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int accentPressed = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int primary = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int primaryDark = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int primaryMuted = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int primaryMutedPressed = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int text_white = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int transparent = 2131165190;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int corner_radius = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int form_margin = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int layer_padding = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int layout_padding = 2131230722;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int apptheme_textfield_activated_holo_light = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apptheme_textfield_default_holo_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int apptheme_textfield_disabled_focused_holo_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int apptheme_textfield_disabled_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int apptheme_textfield_focused_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int flat_selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int helps_logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_social_share = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_launcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int rect_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int register = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c001a
			public const int FinishDetailsInput = 2131492890;
			
			// aapt resource value: 0x7f0c0007
			public const int LayoutDetailsInput = 2131492871;
			
			// aapt resource value: 0x7f0c0002
			public const int LayoutWelcome = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int LayoutWelcomeSub = 2131492867;
			
			// aapt resource value: 0x7f0c0031
			public const int LinearLayout1 = 2131492913;
			
			// aapt resource value: 0x7f0c0008
			public const int Ttoolbar = 2131492872;
			
			// aapt resource value: 0x7f0c001b
			public const int TtoolbarTransparent = 2131492891;
			
			// aapt resource value: 0x7f0c0037
			public const int amvMenu = 2131492919;
			
			// aapt resource value: 0x7f0c0038
			public const int amvMenu2 = 2131492920;
			
			// aapt resource value: 0x7f0c0034
			public const int buttonAddToDo = 2131492916;
			
			// aapt resource value: 0x7f0c0036
			public const int checkToDoItem = 2131492918;
			
			// aapt resource value: 0x7f0c0017
			public const int country = 2131492887;
			
			// aapt resource value: 0x7f0c001d
			public const int forgotLayout = 2131492893;
			
			// aapt resource value: 0x7f0c001f
			public const int forgotPassword = 2131492895;
			
			// aapt resource value: 0x7f0c001e
			public const int forgotStudentId = 2131492894;
			
			// aapt resource value: 0x7f0c002a
			public const int helpsLogo = 2131492906;
			
			// aapt resource value: 0x7f0c0019
			public const int language = 2131492889;
			
			// aapt resource value: 0x7f0c0009
			public const int linearLayout1 = 2131492873;
			
			// aapt resource value: 0x7f0c000f
			public const int linearLayout2 = 2131492879;
			
			// aapt resource value: 0x7f0c000b
			public const int linearLayout3 = 2131492875;
			
			// aapt resource value: 0x7f0c0023
			public const int linearLayout4 = 2131492899;
			
			// aapt resource value: 0x7f0c0026
			public const int linearLayout5 = 2131492902;
			
			// aapt resource value: 0x7f0c0035
			public const int listViewToDo = 2131492917;
			
			// aapt resource value: 0x7f0c002d
			public const int loginBtn = 2131492909;
			
			// aapt resource value: 0x7f0c002c
			public const int loginPassword = 2131492908;
			
			// aapt resource value: 0x7f0c002b
			public const int loginStudentId = 2131492907;
			
			// aapt resource value: 0x7f0c0028
			public const int mainlayout = 2131492904;
			
			// aapt resource value: 0x7f0c003b
			public const int menu_logout = 2131492923;
			
			// aapt resource value: 0x7f0c003a
			public const int menu_refresh = 2131492922;
			
			// aapt resource value: 0x7f0c0039
			public const int menu_share = 2131492921;
			
			// aapt resource value: 0x7f0c0010
			public const int radioButton1 = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int radioButton2 = 2131492881;
			
			// aapt resource value: 0x7f0c0024
			public const int registerEmail = 2131492900;
			
			// aapt resource value: 0x7f0c0021
			public const int registerFirstName = 2131492897;
			
			// aapt resource value: 0x7f0c0022
			public const int registerLastName = 2131492898;
			
			// aapt resource value: 0x7f0c0027
			public const int registerPassword = 2131492903;
			
			// aapt resource value: 0x7f0c0025
			public const int registerStudentId = 2131492901;
			
			// aapt resource value: 0x7f0c0020
			public const int relativeLayout1 = 2131492896;
			
			// aapt resource value: 0x7f0c002e
			public const int relativeLayout6 = 2131492910;
			
			// aapt resource value: 0x7f0c0000
			public const int relativeLayout66 = 2131492864;
			
			// aapt resource value: 0x7f0c0006
			public const int showDetailsInput = 2131492870;
			
			// aapt resource value: 0x7f0c0029
			public const int signInLayout = 2131492905;
			
			// aapt resource value: 0x7f0c0014
			public const int spinnerYear = 2131492884;
			
			// aapt resource value: 0x7f0c0033
			public const int textNewToDo = 2131492915;
			
			// aapt resource value: 0x7f0c001c
			public const int textView1 = 2131492892;
			
			// aapt resource value: 0x7f0c002f
			public const int textView2 = 2131492911;
			
			// aapt resource value: 0x7f0c0030
			public const int textView4 = 2131492912;
			
			// aapt resource value: 0x7f0c0016
			public const int textViewCountry = 2131492886;
			
			// aapt resource value: 0x7f0c0012
			public const int textViewDegree = 2131492882;
			
			// aapt resource value: 0x7f0c000a
			public const int textViewFillUp = 2131492874;
			
			// aapt resource value: 0x7f0c000e
			public const int textViewGender = 2131492878;
			
			// aapt resource value: 0x7f0c0018
			public const int textViewLanguage = 2131492888;
			
			// aapt resource value: 0x7f0c000c
			public const int textViewName = 2131492876;
			
			// aapt resource value: 0x7f0c000d
			public const int textViewNameValue = 2131492877;
			
			// aapt resource value: 0x7f0c0015
			public const int textViewStatus = 2131492885;
			
			// aapt resource value: 0x7f0c0032
			public const int textViewTitle = 2131492914;
			
			// aapt resource value: 0x7f0c0004
			public const int textViewWelcome = 2131492868;
			
			// aapt resource value: 0x7f0c0005
			public const int textViewWelcomeText = 2131492869;
			
			// aapt resource value: 0x7f0c0013
			public const int textViewYear = 2131492883;
			
			// aapt resource value: 0x7f0c0001
			public const int welcomeviewflipper = 2131492865;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_DetailsInput = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_ForgotPassword = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Activity_Register = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Activity_Sign_In = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Activity_To_Do = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Row_List_To_Do = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int toolbar = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int toolbarTransparent = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int activity_main = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int logout = 2131427329;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int blank = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int add_button_text = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int add_textbox_hint = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int checkbox_text = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int menu_refresh = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int mobile_services = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int my_information_header = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int welcome_text = 2131099656;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int AppBaseTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int AppTheme = 2131361793;
			
			// aapt resource value: 0x7f0a0003
			public const int AppTheme_MyToolbar = 2131361795;
			
			// aapt resource value: 0x7f0a0007
			public const int AppTheme_NoStatus = 2131361799;
			
			// aapt resource value: 0x7f0a0004
			public const int AppTheme_SignIn = 2131361796;
			
			// aapt resource value: 0x7f0a0002
			public const int LightDialog = 2131361794;
			
			// aapt resource value: 0x7f0a0008
			public const int _AppTheme = 2131361800;
			
			// aapt resource value: 0x7f0a0006
			public const int standardEditText = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int whiteEditText = 2131361797;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
