#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("helps.Resource", IsApplication=true)]

namespace helps
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int accent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int primary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primaryDark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int apptheme_edit_text_holo_light = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apptheme_textfield_activated_holo_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int apptheme_textfield_default_holo_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int apptheme_textfield_disabled_focused_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int apptheme_textfield_disabled_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int apptheme_textfield_focused_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_social_share = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_launcher = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int register = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int textlines = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000d
			public const int LinearLayout1 = 2131230733;
			
			// aapt resource value: 0x7f080001
			public const int Ttoolbar = 2131230721;
			
			// aapt resource value: 0x7f080013
			public const int amvMenu = 2131230739;
			
			// aapt resource value: 0x7f08000a
			public const int button1 = 2131230730;
			
			// aapt resource value: 0x7f080010
			public const int buttonAddToDo = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int checkToDoItem = 2131230738;
			
			// aapt resource value: 0x7f080007
			public const int imageView1 = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout1 = 2131230722;
			
			// aapt resource value: 0x7f080011
			public const int listViewToDo = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int mainlayout = 2131230725;
			
			// aapt resource value: 0x7f080015
			public const int menu_refresh = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int menu_settings = 2131230742;
			
			// aapt resource value: 0x7f080014
			public const int menu_share = 2131230740;
			
			// aapt resource value: 0x7f080009
			public const int password = 2131230729;
			
			// aapt resource value: 0x7f080004
			public const int register = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int relativeLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int relativeLayout2 = 2131230723;
			
			// aapt resource value: 0x7f08000b
			public const int relativeLayout6 = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int signInLayout = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int studentId = 2131230728;
			
			// aapt resource value: 0x7f08000f
			public const int textNewToDo = 2131230735;
			
			// aapt resource value: 0x7f08000c
			public const int textView2 = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int textViewTitle = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_Register = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_Sign_In = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Activity_To_Do = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Row_List_To_Do = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int toolbar = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int activity_main = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int simple = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int add_button_text = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int add_textbox_hint = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int checkbox_text = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int menu_refresh = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int mobile_services = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int AppTheme_MyToolbar = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int AppTheme_NoStatus = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int _AppTheme = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int standardEditText = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int whiteEditText = 2131099652;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
